# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4389eb0f3b823ee3707b641d0722c044fcaf3ab6cff9cfb6b8900427aa51c3c13dc8d00370a6ce5684d01d06c521f01caaff2545cb19483cd36b437b51487264

test:
  secret_key_base: 73fd4db24b5c16487252b9f99db24537f2a6743e18286e65f42dab3e770460719ba07da44deb3952713e8e0a695798b5a8107d7d7ebd17ff2d5d6da80d1ef781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
